CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, password text NOT NULL, full_name text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE user_roles (user_id uuid NOT NULL REFERENCES users(id), role_id uuid NOT NULL REFERENCES roles(id), PRIMARY KEY (user_id, role_id));
CREATE TABLE sellers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text NOT NULL UNIQUE, commission_rate integer NOT NULL DEFAULT 0 CHECK (commission_rate BETWEEN 0 AND 10000), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE seller_members (seller_id uuid NOT NULL REFERENCES sellers(id), user_id uuid NOT NULL REFERENCES users(id), role text NOT NULL, PRIMARY KEY (seller_id, user_id));
CREATE TABLE refresh_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);

CREATE TABLE categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), parent_id uuid REFERENCES categories(id), name text NOT NULL, slug text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), seller_id uuid NOT NULL REFERENCES sellers(id), name text NOT NULL, slug text NOT NULL UNIQUE, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'draft', metadata_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE product_variants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id uuid NOT NULL REFERENCES products(id), sku text NOT NULL UNIQUE, name text NOT NULL, price bigint NOT NULL CHECK (price >= 0), stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0), attributes jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE product_images (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id uuid NOT NULL REFERENCES products(id), url text NOT NULL, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE product_categories (product_id uuid NOT NULL REFERENCES products(id), category_id uuid NOT NULL REFERENCES categories(id), PRIMARY KEY (product_id, category_id));
CREATE TABLE inventory_movements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), variant_id uuid NOT NULL REFERENCES product_variants(id), quantity integer NOT NULL CHECK (quantity <> 0), type text NOT NULL, reference_id uuid, note text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);

CREATE TABLE shipping_addresses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), recipient_name text NOT NULL, phone text NOT NULL, address_line text NOT NULL, ward text NOT NULL, district text NOT NULL, province text NOT NULL, country text NOT NULL DEFAULT 'VN', postal_code text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE carts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE cart_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), cart_id uuid NOT NULL REFERENCES carts(id), variant_id uuid NOT NULL REFERENCES product_variants(id), quantity integer NOT NULL CHECK (quantity > 0), UNIQUE (cart_id, variant_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), status text NOT NULL DEFAULT 'pending', currency char(3) NOT NULL DEFAULT 'VND', subtotal bigint NOT NULL DEFAULT 0 CHECK (subtotal >= 0), discount bigint NOT NULL DEFAULT 0 CHECK (discount >= 0), shipping_fee bigint NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0), total bigint NOT NULL DEFAULT 0 CHECK (total >= 0), shipping_address_id uuid NOT NULL REFERENCES shipping_addresses(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE seller_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES orders(id), seller_id uuid NOT NULL REFERENCES sellers(id), status text NOT NULL DEFAULT 'pending', subtotal bigint NOT NULL DEFAULT 0, commission bigint NOT NULL DEFAULT 0, total bigint NOT NULL DEFAULT 0, UNIQUE (order_id, seller_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), seller_order_id uuid NOT NULL REFERENCES seller_orders(id), variant_id uuid NOT NULL REFERENCES product_variants(id), product_name text NOT NULL, sku text NOT NULL, variant_name text NOT NULL, unit_price bigint NOT NULL CHECK (unit_price >= 0), quantity integer NOT NULL CHECK (quantity > 0), discount bigint NOT NULL DEFAULT 0 CHECK (discount >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);

CREATE TABLE payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL UNIQUE REFERENCES orders(id), method text NOT NULL, status text NOT NULL DEFAULT 'pending', amount bigint NOT NULL CHECK (amount >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE payment_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), payment_id uuid NOT NULL REFERENCES payments(id), provider text NOT NULL, provider_transaction_id text NOT NULL, status text NOT NULL, amount bigint NOT NULL CHECK (amount >= 0), UNIQUE (provider, provider_transaction_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE shipments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), seller_order_id uuid NOT NULL UNIQUE REFERENCES seller_orders(id), carrier text NOT NULL DEFAULT '', tracking_number text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE shipment_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), shipment_id uuid NOT NULL REFERENCES shipments(id), status text NOT NULL, description text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);

CREATE TABLE coupons (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, type text NOT NULL, value bigint NOT NULL CHECK (value >= 0), starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, usage_limit integer NOT NULL DEFAULT 0, used_count integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE coupon_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), coupon_id uuid NOT NULL REFERENCES coupons(id), min_order bigint NOT NULL DEFAULT 0, seller_id uuid REFERENCES sellers(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE coupon_redemptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), coupon_id uuid NOT NULL REFERENCES coupons(id), user_id uuid NOT NULL REFERENCES users(id), order_id uuid NOT NULL REFERENCES orders(id), UNIQUE (coupon_id, user_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE reviews (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), product_id uuid NOT NULL REFERENCES products(id), order_item_id uuid, rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5), comment text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'published', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE wishlists (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE wishlist_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), wishlist_id uuid NOT NULL REFERENCES wishlists(id), product_id uuid NOT NULL REFERENCES products(id), UNIQUE (wishlist_id, product_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE outbox_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), aggregate_type text NOT NULL, aggregate_id uuid NOT NULL, event_type text NOT NULL, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'pending', retry_count integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE INDEX idx_outbox_pending ON outbox_events (available_at) WHERE status = 'pending';
